# Generated by Django 3.2.5 on 2022-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20220805_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/portal/default_avatar.jpg', upload_to='avatars/'),
        ),
    ]
