# Generated by Django 3.2.5 on 2022-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(None, 'Would rather not specify'), (1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
