# Generated by Django 4.0.6 on 2022-08-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_course_day_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day_2',
            field=models.IntegerField(choices=[(None, '-'), (0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday')], null=True),
        ),
    ]
