# Generated by Django 4.0.6 on 2022-08-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_course_day_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='day_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='day_2',
        ),
    ]
