# Generated by Django 4.0.6 on 2022-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_course_day_1_remove_course_day_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day_1',
            field=models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='day_2',
            field=models.IntegerField(blank=True, choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday')], null=True),
        ),
    ]
